Document: kirk
Title: Debian kirk Manual
Author: <insert document author here>
Abstract: This manual describes what kirk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kirk/kirk.sgml.gz

Format: postscript
Files: /usr/share/doc/kirk/kirk.ps.gz

Format: text
Files: /usr/share/doc/kirk/kirk.text.gz

Format: HTML
Index: /usr/share/doc/kirk/html/index.html
Files: /usr/share/doc/kirk/html/*.html
